"""Reporting system for the Cybersecurity Toolkit."""
import json
import os
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List, Optional
import jinja2
from jinja2 import Environment, FileSystemLoader
import logging

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generates security reports in various formats."""
    
    def __init__(self, output_dir: str = "~/cybersec_reports"):
        """Initialize report generator.
        
        Args:
            output_dir: Directory to store reports
        """
        self.output_dir = Path(output_dir).expanduser()
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.template_dir = Path(__file__).parent.parent / "config" / "templates"
        
        # Create default templates if they don't exist
        self._create_default_templates()
    
    def _create_default_templates(self):
        """Create default report templates if they don't exist."""
        templates_dir = self.template_dir
        templates_dir.mkdir(parents=True, exist_ok=True)
        
        # Markdown template
        markdown_template = """# Cybersecurity Scan Report

**Generated:** {{ timestamp }}
**System:** {{ system_info.hostname }} ({{ system_info.os }})
**Scan Type:** {{ scan_type }}
**Duration:** {{ duration }} seconds

## Summary
- **Critical Issues:** {{ summary.critical }}
- **High Issues:** {{ summary.high }}
- **Medium Issues:** {{ summary.medium }}
- **Low Issues:** {{ summary.low }}
- **Total Issues:** {{ summary.total }}

## System Information
- **Hostname:** {{ system_info.hostname }}
- **OS:** {{ system_info.os }}
- **Kernel:** {{ system_info.kernel }}
- **Uptime:** {{ system_info.uptime }}
- **Load Average:** {{ system_info.load_avg }}

{% if findings.system %}
## System Findings
{% for finding in findings.system %}
### {{ finding.title }}
- **Severity:** {{ finding.severity }}
- **Description:** {{ finding.description }}
- **Recommendation:** {{ finding.recommendation }}
- **Location:** {{ finding.location }}

{% endfor %}
{% endif %}

{% if findings.network %}
## Network Findings
{% for finding in findings.network %}
### {{ finding.title }}
- **Severity:** {{ finding.severity }}
- **Description:** {{ finding.description }}
- **Recommendation:** {{ finding.recommendation }}
- **Location:** {{ finding.location }}

{% endfor %}
{% endif %}

{% if findings.docker %}
## Docker Findings
{% for finding in findings.docker %}
### {{ finding.title }}
- **Severity:** {{ finding.severity }}
- **Description:** {{ finding.description }}
- **Recommendation:** {{ finding.recommendation }}
- **Location:** {{ finding.location }}

{% endfor %}
{% endif %}

{% if findings.firewall %}
## Firewall Findings
{% for finding in findings.firewall %}
### {{ finding.title }}
- **Severity:** {{ finding.severity }}
- **Description:** {{ finding.description }}
- **Recommendation:** {{ finding.recommendation }}
- **Location:** {{ finding.location }}

{% endfor %}
{% endif %}

## Recommendations
{% for rec in recommendations %}
- {{ rec }}

{% endfor %}

---
*Generated by Cybersecurity Toolkit v{{ version }}*
"""
        
        # HTML template
        html_template = """<!DOCTYPE html>
<html>
<head>
    <title>Cybersecurity Scan Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { background-color: #f0f0f0; padding: 15px; border-radius: 5px; }
        .summary { background-color: #e8f4f8; padding: 15px; margin: 10px 0; border-radius: 5px; }
        .finding { border: 1px solid #ddd; margin: 10px 0; padding: 10px; border-radius: 5px; }
        .critical { border-left: 5px solid #ff0000; }
        .high { border-left: 5px solid #ff6600; }
        .medium { border-left: 5px solid #ffcc00; }
        .low { border-left: 5px solid #0066cc; }
        .severity { font-weight: bold; }
        .recommendation { background-color: #f9f9f9; padding: 5px; margin-top: 5px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Cybersecurity Scan Report</h1>
        <p><strong>Generated:</strong> {{ timestamp }}</p>
        <p><strong>System:</strong> {{ system_info.hostname }} ({{ system_info.os }})</p>
        <p><strong>Scan Type:</strong> {{ scan_type }}</p>
        <p><strong>Duration:</strong> {{ duration }} seconds</p>
    </div>

    <div class="summary">
        <h2>Summary</h2>
        <ul>
            <li><strong>Critical Issues:</strong> {{ summary.critical }}</li>
            <li><strong>High Issues:</strong> {{ summary.high }}</li>
            <li><strong>Medium Issues:</strong> {{ summary.medium }}</li>
            <li><strong>Low Issues:</strong> {{ summary.low }}</li>
            <li><strong>Total Issues:</strong> {{ summary.total }}</li>
        </ul>
    </div>

    <h2>System Information</h2>
    <ul>
        <li><strong>Hostname:</strong> {{ system_info.hostname }}</li>
        <li><strong>OS:</strong> {{ system_info.os }}</li>
        <li><strong>Kernel:</strong> {{ system_info.kernel }}</li>
        <li><strong>Uptime:</strong> {{ system_info.uptime }}</li>
        <li><strong>Load Average:</strong> {{ system_info.load_avg }}</li>
    </ul>

    {% if findings.system %}
    <h2>System Findings</h2>
    {% for finding in findings.system %}
    <div class="finding {{ finding.severity|lower }}">
        <h3>{{ finding.title }}</h3>
        <p><span class="severity">Severity:</span> {{ finding.severity }}</p>
        <p><strong>Description:</strong> {{ finding.description }}</p>
        <p><strong>Recommendation:</strong> {{ finding.recommendation }}</p>
        <p><strong>Location:</strong> {{ finding.location }}</p>
    </div>
    {% endfor %}
    {% endif %}

    {% if findings.network %}
    <h2>Network Findings</h2>
    {% for finding in findings.network %}
    <div class="finding {{ finding.severity|lower }}">
        <h3>{{ finding.title }}</h3>
        <p><span class="severity">Severity:</span> {{ finding.severity }}</p>
        <p><strong>Description:</strong> {{ finding.description }}</p>
        <p><strong>Recommendation:</strong> {{ finding.recommendation }}</p>
        <p><strong>Location:</strong> {{ finding.location }}</p>
    </div>
    {% endfor %}
    {% endif %}

    {% if findings.docker %}
    <h2>Docker Findings</h2>
    {% for finding in findings.docker %}
    <div class="finding {{ finding.severity|lower }}">
        <h3>{{ finding.title }}</h3>
        <p><span class="severity">Severity:</span> {{ finding.severity }}</p>
        <p><strong>Description:</strong> {{ finding.description }}</p>
        <p><strong>Recommendation:</strong> {{ finding.recommendation }}</p>
        <p><strong>Location:</strong> {{ finding.location }}</p>
    </div>
    {% endfor %}
    {% endif %}

    {% if findings.firewall %}
    <h2>Firewall Findings</h2>
    {% for finding in findings.firewall %}
    <div class="finding {{ finding.severity|lower }}">
        <h3>{{ finding.title }}</h3>
        <p><span class="severity">Severity:</span> {{ finding.severity }}</p>
        <p><strong>Description:</strong> {{ finding.description }}</p>
        <p><strong>Recommendation:</strong> {{ finding.recommendation }}</p>
        <p><strong>Location:</strong> {{ finding.location }}</p>
    </div>
    {% endfor %}
    {% endif %}

    <h2>Recommendations</h2>
    <ul>
        {% for rec in recommendations %}
        <li>{{ rec }}</li>
        {% endfor %}
    </ul>

    <hr>
    <p><em>Generated by Cybersecurity Toolkit v{{ version }}</em></p>
</body>
</html>
"""
        
        # JSON template (just for reference, JSON is handled directly)
        json_example = {
            "timestamp": "{{ timestamp }}",
            "system_info": "{{ system_info }}",
            "scan_type": "{{ scan_type }}",
            "duration": "{{ duration }}",
            "summary": "{{ summary }}",
            "findings": "{{ findings }}",
            "recommendations": "{{ recommendations }}",
            "version": "{{ version }}"
        }
        
        # Write templates
        with open(templates_dir / "report_markdown.jinja2", "w", encoding="utf-8") as f:
            f.write(markdown_template)
        
        with open(templates_dir / "report_html.jinja2", "w", encoding="utf-8") as f:
            f.write(html_template)
        
        with open(templates_dir / "report_json.jinja2", "w", encoding="utf-8") as f:
            json.dump(json_example, f, indent=2)
    
    def generate_report(self, data: Dict[str, Any], format_type: str = "markdown", 
                       filename: Optional[str] = None) -> str:
        """Generate a report in the specified format.
        
        Args:
            data: Report data to use in template
            format_type: Output format ('markdown', 'html', 'json', 'txt')
            filename: Optional filename to save report (if None, generates one)
            
        Returns:
            Path to generated report file
        """
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            extension = {
                "markdown": ".md",
                "html": ".html", 
                "json": ".json",
                "txt": ".txt"
            }.get(format_type, ".md")
            filename = f"cybersec_report_{timestamp}{extension}"
        
        output_path = self.output_dir / filename
        
        if format_type == "json":
            with open(output_path, "w", encoding="utf-8") as f:
                json.dump(data, f, indent=2, default=str)
        else:
            # Use Jinja2 for templating
            env = Environment(loader=FileSystemLoader(str(self.template_dir)))
            
            template_name = f"report_{format_type}.jinja2"
            try:
                template = env.get_template(template_name)
                content = template.render(**data)
                
                with open(output_path, "w", encoding="utf-8") as f:
                    f.write(content)
            except jinja2.TemplateNotFound:
                logger.error(f"Template {template_name} not found, using basic format")
                # Fallback to basic format
                with open(output_path, "w", encoding="utf-8") as f:
                    f.write(self._basic_format_report(data, format_type))
        
        logger.info(f"Report generated: {output_path}")
        return str(output_path)
    
    def _basic_format_report(self, data: Dict[str, Any], format_type: str) -> str:
        """Generate a basic report when template is not available."""
        if format_type == "html":
            content = f"""
            <h1>Cybersecurity Report</h1>
            <p>Generated: {data.get('timestamp', 'N/A')}</p>
            <p>System: {data.get('system_info', {}).get('hostname', 'N/A')}</p>
            <p>Scan Type: {data.get('scan_type', 'N/A')}</p>
            """
        elif format_type == "txt":
            content = f"""
Cybersecurity Report
===================
Generated: {data.get('timestamp', 'N/A')}
System: {data.get('system_info', {}).get('hostname', 'N/A')}
Scan Type: {data.get('scan_type', 'N/A')}
"""
        else:  # markdown
            content = f"""
# Cybersecurity Report

**Generated:** {data.get('timestamp', 'N/A')}  
**System:** {data.get('system_info', {}).get('hostname', 'N/A')}  
**Scan Type:** {data.get('scan_type', 'N/A')}
"""
        
        return content


class ReportHistory:
    """Manages history of generated reports."""
    
    def __init__(self, max_reports: int = 10):
        """Initialize report history.
        
        Args:
            max_reports: Maximum number of reports to keep
        """
        self.max_reports = max_reports
        self.reports_dir = Path.home() / ".cybersec" / "reports"
        self.reports_dir.mkdir(parents=True, exist_ok=True)
    
    def get_recent_reports(self, limit: int = 10) -> List[Dict[str, Any]]:
        """Get list of recent reports.
        
        Args:
            limit: Maximum number of reports to return
            
        Returns:
            List of report information
        """
        reports = []
        for report_file in self.reports_dir.glob("*"):
            if report_file.is_file():
                stat = report_file.stat()
                reports.append({
                    "name": report_file.name,
                    "size": stat.st_size,
                    "modified": datetime.fromtimestamp(stat.st_mtime),
                    "path": str(report_file)
                })
        
        # Sort by modification time (newest first)
        reports.sort(key=lambda x: x["modified"], reverse=True)
        return reports[:limit]
    
    def cleanup_old_reports(self):
        """Remove old reports to maintain max_reports limit."""
        reports = self.get_recent_reports(limit=100)  # Get all reports
        
        if len(reports) > self.max_reports:
            # Remove oldest reports
            for report in reports[self.max_reports:]:
                try:
                    os.remove(report["path"])
                    logger.info(f"Removed old report: {report['path']}")
                except OSError as e:
                    logger.error(f"Could not remove old report {report['path']}: {e}")